### ISSUE TITLE
Sharpness Indicator computation

### ISSUE THREAD

**Issue by ElisonSherton** [subpic/koniq#11]
Hi everyone!

I wanted to understand if the source code for computation of indicators is available in the repo or anywhere in open-source. Especially wanted to understand how the sharpness indicator estimation from the resource 50 cited in the paper in section 3.4.1 as shown below.

![image](https://github.com/subpic/koniq/assets/45599762/e159f623-0ac0-4ac0-b31d-fe1b43ba33cb)

Could anyone kindly help with this?

Regards,
Vinayak.

**Comment by subpic** [comment]
The code for the sharpness indicator is here: [fish.zip](https://github.com/subpic/koniq/files/11555000/fish.zip)

Best,
Vlad

**Comment by ElisonSherton** [comment]
Thank you so much @subpic!

I will try this out on my end and let you know if I get any doubts. Appreciate the response.

Regards,
Vinayak.
