### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by PhenomenalOnee** [subpic/koniq#2]
Thanks for the wonderfull work
I have one request
can how provide a single image testing demo for the KonCept224 and KonCept512 models
Thanks

**Comment by subpic** [comment]
Hi,

After loading a [KonCept model](https://github.com/subpic/koniq/blob/master/train_koncept512.ipynb) (skipping the training step) you can do this:

```# Load an image
from kutils import image_utils as iu
!wget -O image.jpg http://database.mmsp-kn.de/uploads/1/1/9/4/119489445/indic-sharpness-5_orig.jpg
im = preprocess_fn(iu.read_image('image.jpg'))

# Create a batch to feed to the model
batch = np.expand_dims(im, 0)

# Predict the image's quality score
y_pred = model.predict(batch)
print('Score:', np.round(y_pred,2))
```

Best,
Vlad
