### ISSUE TITLE
Brightness, Colorfulness, Contrast & Sharpness

### ISSUE THREAD

**Issue by abduallahmohamed** [subpic/koniq#4]
Hi, 

I was wondering where is this info in the dataset labels? 

as shown on your homepage. 

Thanks

**Comment by subpic** [comment]
Hi,

I've updated the home page; it now includes a download link for the indicators:
http://datasets.vqa.mmsp-kn.de/archives/koniq10k_indicators.zip

Best,
Vlad

**Comment by abduallahmohamed** [comment]
Thanks! One last question: How are these indicators are measured?

**Comment by subpic** [comment]
We described the methods and references in the [KonIQ-10k paper](https://arxiv.org/pdf/1910.06180.pdf). Is this what you were asking?

**Comment by abduallahmohamed** [comment]
Thanks!
