### ISSUE TITLE
How to use this model to evaluate IQ of any image. 

### ISSUE THREAD

**Issue by pbhattac1286** [subpic/koniq#9]

**Comment by subpic** [comment]
See the last section "Predict on a custom image (example)" in the notebook: [koncept512_train_test_py3_with_kuti.ipynb](https://github.com/subpic/koniq/blob/master/koncept512_train_test_py3_with_kuti.ipynb)

**Comment by pbhattac1286** [comment]
Yes used the same .Got predicted mos value.How to infer this value
